language: java
jdk:
  - oraclejdk8

env:
  global:
      - secure: "ARA7C8Umg2WtMFR8N1O7+15ZKleoXXWQu7/MBFwymLHKoPVapW4GPu8DR/RobHKUcuRdIloGMjp1JKXAKsOt1WH/Or+nZkJiOSsi2EJ7gWtIZwF427rxjE6xWE3FqqhOSvJJwzmQOyAOllRAq4sfvLOeAdkEAgCHROOFMeCOpyeOhQCvrTT8YDBbtE2iJavN7AaSr//dMGa3t4liTHWh1VkWJtG9dePyxJs2n7JlYZk9EUPgqNY1hs8MeVl+u4lt6ylwOXovJV2YLTrxgEEYGNrdn7N2XjPhnBcLZDG2gnDFUNlvuKDYNHKWs2hIWoVrpndApiTRh2SHF9kcqH3o0NuRMPho5/+bPUnqrn9eYfmp7hcDSH6Bp0Byq+8b24Q2qC/2hEFjrkNcJX/7Y2JETkD+Xkzuowrg++QbYUNTpjKuxhRij+KnBnoo3o29UryTqJmjyOtCmEqBbzhluJpcE8Qnmr1xgbfsJqxX15mvHJU6LDx5sBmpNVoAQZIXjr5KlxeLtxyXzqiTttJBkDeOzd6le8f20trwApQ3Dyv+Qa0EQzH79CGihHq7vRieZud9N5mdbt82SsfQNF03CWGqsPh2i6zW/Gd3pGVCYG+SfQuRNfHcgnpmL3fqbASNpXnifnnfN44IRp1qsprrg3ORQ6vwoBn4MBlM6flC+BIiU4I="

after_success:
  - mvn deploy --settings settings.xml
